# Imports

In [1]:
!pip install -r ../requirements.txt

Collecting pysus
  Using cached pysus-1.0.1-py3-none-any.whl (1.4 MB)
Requirement already satisfied: pandas in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from -r ../requirements.txt (line 2)) (2.3.3)
Requirement already satisfied: numpy in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from -r ../requirements.txt (line 3)) (2.2.6)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Requirement already satisfied: python-dateutil==2.8.2 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (4.15.0)
Collecting elasticsearch[preprocessing]==7.16.2
  Using cached elasticsearch-7.16.2-py2.py3-none-any.whl (385 kB)
Collecting pyreaddbc>=1.1.0
  Using cached pyreaddbc-1.2.0-cp310-cp310-manylinux_2_35_x86_64.whl
Collecting dateparser<2.0.0,>=1.1.8
  Using cached dateparser-1.3.0-py3-none-any.whl (318 kB)
Collecting fastparquet<=2024.11.0,>=2023.10.1
  Using cached fastparquet-2024.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
Requirement already satisfied: tqdm==4.64.0 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (4.64.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: aioftp<0.22.0,>=0.21.4 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (0.21.4)
Requirement already satisfied: pyarrow>=11.0.0 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (23.0.1)
Requirement already satisfied: urwid<3.0.0,>=2.1.2 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (2.6.16)
Requirement already satisfied: pycparser==2.21 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (2.21)
Requirement already satisfied: wget<4.0,>=3.2 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (3.2)
Requirement already satisfied: bigtree<0.13.0,>=0.12.2 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (0.12.5)
Requirement already satisfied: dbfread==2.0.7 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pysus->-r ../requirements.txt (line 1)) (1.4.0)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: certifi in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from elasticsearch[preprocessing]==7.16.2->pysus->-r ../requirements.txt (line 1)) (2026.2.25)
Requirement already satisfied: urllib3<2,>=1.21.1 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from elasticsearch[preprocessing]==7.16.2->pysus->-r ../requirements.txt (line 1)) (1.26.20)
Requirement already satisfied: six>=1.5 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from python-dateutil==2.8.2->pysus->-r ../requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: tzdata>=2022.7 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pandas->-r ../requirements.txt (line 2)) (2025.3)
Requirement already satisfied: pytz>=2020.1 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pandas->-r ../requirements.txt (line 2)) (2026.1.post1)
Requirement already satisfied: fonttools>=4.22.0 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from matplotlib->-r ../requirements.txt (line 4)) (4.62.1)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from matplotlib->-r ../requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: cycler>=0.10 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from matplotlib->-r ../requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: pillow>=8 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from matplotlib->-r ../requirements.txt (line 4)) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from matplotlib->-r ../requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: packaging>=20.0 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from matplotlib->-r ../requirements.txt (line 4)) (26.0)
Requirement already satisfied: regex>=2024.9.11 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from dateparser<2.0.0,>=1.1.8->pysus->-r ../requirements.txt (line 1)) (2026.2.28)
Requirement already satisfied: tzlocal>=0.2 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from dateparser<2.0.0,>=1.1.8->pysus->-r ../requirements.txt (line 1)) (5.3.1)
Requirement already satisfied: cramjam>=2.3 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus->-r ../requirements.txt (line 1)) (2.11.0)
Requirement already satisfied: fsspec in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus->-r ../requirements.txt (line 1)) (2026.2.0)
Collecting cffi<2,>=1.15.1
  Using cached cffi-1.17.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (446 kB)
Requirement already satisfied: pyyaml>=6 in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from pyreaddbc>=1.1.0->pysus->-r ../requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: wcwidth in /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages (from urwid<3.0.0,>=2.1.2->pysus->-r ../requirements.txt (line 1)) (0.6.0)
Installing collected packages: elasticsearch, contourpy, cffi, pyreaddbc, matplotlib, dateparser, seaborn, fastparquet, pysus
  Attempting uninstall: cffi
    Found existing installation: cffi 2.0.0
    Uninstalling cffi-2.0.0:
      Successfully uninstalled cffi-2.0.0
Successfully installed cffi-1.17.1 contourpy-1.3.2 dateparser-1.3.0 elasticsearch-7.16.2 fastparquet-2024.11.0 matplotlib-3.10.8 pyreaddbc-1.2.0 pysus-1.0.1 seaborn-0.13.2

In [2]:
from pysus import SINAN
import pandas as pd

# Data acquisition

In [3]:
sinan = SINAN().load()

In [4]:
files = sinan.get_files(dis_code=['MALA'])

In [5]:
parquet = sinan.download(files)

MALABR06.parquet:   0%|          | 0.00/4.65k [00:00<?, ?B/s]    /home/fuganti/Projects/Health_EDA/venv./lib/python3.10/site-packages/tqdm/std.py:533: TqdmWarning: clamping frac to range [0, 1]
  full_bar = Bar(frac,
MALABR24.parquet: 100%|█████████▉| 3.77k/3.77k [00:00<00:00, 53.4kB/s]

In [6]:
df = None
for p in parquet:
    p.to_dataframe()
    df = pd.concat([df, p.to_dataframe()])

In [7]:
display(df)

,ID_MUNICIP,ID_UNIDADE,DT_NOTIFIC,CS_RACA,CS_ESCOLAR,NU_ANO,SEM_NOT,SG_UF_NOT,ID_REGIONA,DT_SIN_PRI,...,DT_ENCERRA,DT_DIGITA,DT_TRANSUS,DT_TRANSDM,DT_TRANSSM,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H
0,2708006,2004054,2004-01-26,4,3,2004,042004,AL,008,2004-01-20,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2704302,0008133,2004-02-04,,,2004,052004,AL,,2004-01-02,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2704302,2720035,2004-01-06,4,9,2004,012004,AL,001,2003-12-30,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2704302,2720035,2004-01-07,1,9,2004,012004,AL,001,2004-01-01,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2704302,2720035,2004-01-02,4,9,2004,532003,AL,001,2004-01-01,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,320530,11746,2024-12-16,4,<NA>,2024,202450,32,32002,2024-12-16,...,20241218,20241216,,,,,,,,
2267,320520,2445069,2024-12-27,4,<NA>,2024,202451,32,32002,2024-12-25,...,20250101,20241227,,,,,,,,
2268,320530,11800,2024-12-30,4,<NA>,2024,202452,32,32002,2024-12-29,...,20241231,20241230,,,,,,,,
2269,320530,11738,2024-11-17,3,<NA>,2024,202446,32,32002,2024-11-16,...,20250108,20241117,,,,,,,,
2270,320530,11738,2024-07-03,4,<NA>,2024,202426,32,32002,2024-07-02,...,20240718,20240703,,,,,,,,

In [11]:
df.to_csv('../data/malaria.csv', index=False)

# EDA

In [12]:
df.describe()

,ID_MUNICIP,ID_UNIDADE,DT_NOTIFIC,CS_RACA,CS_ESCOLAR,NU_ANO,SEM_NOT,SG_UF_NOT,ID_REGIONA,DT_SIN_PRI,...,DT_ENCERRA,DT_DIGITA,DT_TRANSUS,DT_TRANSDM,DT_TRANSSM,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H
count,68320,68320,68320,68320,12026,68320,68320,68320,68320,68320,...,56294,56294,56294,56294,56294,56294,56294,56294,56294,56294
unique,2642,6183,7216,7,8,21,1203,45,300,7764,...,591,4826,1525,668,3989,1,847,569,1,1
top,330455,2506661,2018-08-09,4,3,2018,201832,32,,2018-08-09,...,,,,,,,,,,
freq,3676,2805,464,28141,2996,7939,1917,9654,10892,437,...,55101,216,53828,55126,34713,56294,53848,51751,56294,56294

In [13]:
df.isna().sum()

ID_MUNICIP        0
ID_UNIDADE        0
DT_NOTIFIC        0
CS_RACA           0
CS_ESCOLAR    56294
              ...
DT_TRANSRM    12026
DT_TRANSRS    12026
DT_TRANSSE    12026
NU_LOTE_V     12026
NU_LOTE_H     12026
Length: 102, dtype: int64

In [14]:
df.columns

Index(['ID_MUNICIP', 'ID_UNIDADE', 'DT_NOTIFIC', 'CS_RACA', 'CS_ESCOLAR',
       'NU_ANO', 'SEM_NOT', 'SG_UF_NOT', 'ID_REGIONA', 'DT_SIN_PRI',
       ...
       'DT_ENCERRA', 'DT_DIGITA', 'DT_TRANSUS', 'DT_TRANSDM', 'DT_TRANSSM',
       'DT_TRANSRM', 'DT_TRANSRS', 'DT_TRANSSE', 'NU_LOTE_V', 'NU_LOTE_H'],
      dtype='object', length=102)

In [15]:
list = df.columns.tolist()

In [ ]:
print(list) #PMALARIA AMALARIA??? - nada sobre no pdf de descrição do dataset, provavelmente não é tão relevante

['ID_MUNICIP', 'ID_UNIDADE', 'DT_NOTIFIC', 'CS_RACA', 'CS_ESCOLAR', 'NU_ANO', 'SEM_NOT', 'SG_UF_NOT', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'NU_IDADE', 'CS_SEXO', 'ID_MN_RESI', 'SG_UF', 'ID_PAIS', 'ID_DG_NOT', 'ID_EV_NOT', 'ANT_DT_INV', 'OCUPACAO', 'TRANSFU', 'DTTRANSFU', 'UTRANSFU', 'UFTRANSFU', 'PTRANSFU', 'MTRANSFU', 'PUSUARIO', 'PMALARIA', 'AMALARIA', 'ASSINTOM', 'FEBRE', 'CALAFRIO', 'SUDORESE', 'CLI_OUTRO', 'CD_OUTRO', 'GESTANTE', 'HOSPITAL', 'DINTERNA', 'UFINTERNA', 'MINTERNA', 'DEXAME', 'PMM', 'PCRUZ', 'RESULT', 'CLOROQ', 'PRIMAQ', 'TETRAC', 'MEFLOQ', 'ARTESU', 'QUININO', 'ARTEM', 'CLIND', 'CLOROQI', 'QUININOI', 'ARTEI', 'ARTEMI', 'CLINDI', 'DOXOCI', 'SOUTROS', 'DTRATA', 'CON_CLASSI', 'CON_CONFIR', 'CON_INF_MU', 'CON_INF_UF', 'CON_INF_PA', 'CON_DOENCA', 'CON_EVOLUC', 'CON_DT_OBI', 'CON_DT_ENC', 'IN_VINCULA', 'NDUPLIC', 'TP_NOT', 'ID_AGRAVO', 'ANO_NASC', 'NU_IDADE_N', 'CS_GESTANT', 'CS_ESCOL_N', 'ID_RG_RESI', 'DT_INVEST', 'ID_OCUPA_N', 'CLASSI_FIN', 'AT_ATIVIDA', 'AT_LAMINA', 'AT_SINTOMA', 'TPAUTOCTO', 'COUFINF', 'COPAISINF', 'COMUNINF', 'LOC_INF', 'TRA_ESQUEM', 'DSTRAESQUE', 'NU_LOTE_I', 'DT_ENCERRA', 'DT_DIGITA', 'DT_TRANSUS', 'DT_TRANSDM', 'DT_TRANSSM', 'DT_TRANSRM', 'DT_TRANSRS', 'DT_TRANSSE', 'NU_LOTE_V', 'NU_LOTE_H']

In [17]:
print(df['AMALARIA'].unique())

<StringArray>
['1A  ',     '', '60D ', '34D ', '02M ', '45D ', '03M ', '3M  ', '7M  ',
 'M   ',
 ...
 '+ 1A', '12 A', '2D  ', '40M ', '0A  ', '60M ', '18 D', '26M ', '01 M',
   <NA>]
Length: 252, dtype: string