#***Disciplina de Aprendizado de Máquina Aplicado a Problemas (2026) - SME0860***
---
Alunos:
1. João Pedro
2. Julio Cesar A A Fuganti - 15638792
3. Victor Silva Botelho - 15645421

## *Imports*

In [1]:
!pip install -r /content/requirements.txt

Requirement already satisfied: pysus in /usr/local/lib/python3.12/dist-packages (from -r /content/requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r /content/requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r /content/requirements.txt (line 3)) (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r /content/requirements.txt (line 4)) (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from -r /content/requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: aioftp<0.22.0,>=0.21.4 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (0.21.4)
Requirement already satisfied: bigtree<0.13.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (0.12.5)
Requirement already satisfied: dateparser<2.0.0,>=1.1.8 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: dbfread==2.0.7 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: elasticsearch==7.16.2 in /usr/local/lib/python3.12/dist-packages (from elasticsearch[preprocessing]==7.16.2->pysus->-r /content/requirements.txt (line 1)) (7.16.2)
Requirement already satisfied: fastparquet<=2024.11.0,>=2023.10.1 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (2024.11.0)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (18.1.0)
Requirement already satisfied: pycparser==2.21 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (2.21)
Requirement already satisfied: pyreaddbc>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: tqdm==4.64.0 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (4.64.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: urwid<3.0.0,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (2.6.16)
Requirement already satisfied: wget<4.0,>=3.2 in /usr/local/lib/python3.12/dist-packages (from pysus->-r /content/requirements.txt (line 1)) (3.2)
Requirement already satisfied: urllib3<2,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus->-r /content/requirements.txt (line 1)) (1.26.20)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus->-r /content/requirements.txt (line 1)) (2026.2.25)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil==2.8.2->pysus->-r /content/requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r /content/requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r /content/requirements.txt (line 2)) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/requirements.txt (line 4)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/requirements.txt (line 4)) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/requirements.txt (line 4)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus->-r /content/requirements.txt (line 1)) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus->-r /content/requirements.txt (line 1)) (5.3.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus->-r /content/requirements.txt (line 1)) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus->-r /content/requirements.txt (line 1)) (2025.3.0)
Requirement already satisfied: cffi<2,>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from pyreaddbc>=1.1.0->pysus->-r /content/requirements.txt (line 1)) (1.17.1)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.12/dist-packages (from pyreaddbc>=1.1.0->pysus->-r /content/requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from urwid<3.0.0,>=2.1.2->pysus->-r /content/requirements.txt (line 1)) (0.6.0)

In [2]:
from pysus import SINAN
import pandas as pd

# *Aquisição de Dados*

In [3]:
sinan = SINAN().load()
sinan.diseases

{'ACBI': 'Acidente de trabalho com material biológico',
 'ACGR': 'Acidente de trabalho',
 'ANIM': 'Acidente por Animais Peçonhentos',
 'ANTR': 'Atendimento Antirrabico',
 'BOTU': 'Botulismo',
 'CANC': 'Cancêr relacionado ao trabalho',
 'CHAG': 'Doença de Chagas Aguda',
 'CHIK': 'Febre de Chikungunya',
 'COLE': 'Cólera',
 'COQU': 'Coqueluche',
 'DENG': 'Dengue',
 'DERM': 'Dermatoses ocupacionais',
 'DIFT': 'Difteria',
 'ESQU': 'Esquistossomose',
 'EXAN': 'Doença exantemáticas',
 'FMAC': 'Febre Maculosa',
 'FTIF': 'Febre Tifóide',
 'HANS': 'Hanseníase',
 'HANT': 'Hantavirose',
 'HEPA': 'Hepatites Virais',
 'IEXO': 'Intoxicação Exógena',
 'INFL': 'Influenza Pandêmica',
 'LEIV': 'Leishmaniose Visceral',
 'LEPT': 'Leptospirose',
 'LERD': 'LER/Dort',
 'LTAN': 'Leishmaniose Tegumentar Americana',
 'MALA': 'Malária',
 'MENI': 'Meningite',
 'MENT': 'Transtornos mentais relacionados ao trabalho',
 'NTRA': 'Notificação de Tracoma',
 'PAIR': 'Perda auditiva por ruído relacionado ao trabalho',
 'PEST': 'Peste',
 'PFAN': 'Paralisia Flácida Aguda',
 'PNEU': 'Pneumoconioses realacionadas ao trabalho',
 'RAIV': 'Raiva',
 'SDTA': 'Surto Doenças Transmitidas por Alimentos',
 'SIFA': 'Sífilis Adquirida',
 'SIFC': 'Sífilis Congênita',
 'SIFG': 'Sífilis em Gestante',
 'SRC': 'Síndrome da Rubéola Congênia',
 'TETA': 'Tétano Acidental',
 'TETN': 'Tétano Neonatal',
 'TOXC': 'Toxoplasmose Congênita',
 'TOXG': 'Toxoplasmose Gestacional',
 'TRAC': 'Inquérito de Tracoma',
 'TUBE': 'Tuberculose',
 'VARC': 'Varicela',
 'VIOL': 'Violência doméstica, sexual e/ou outras violências',
 'ZIKA': 'Zika Vírus'}

In [4]:
files = sinan.get_files(dis_code=['MALA'])

In [5]:
parquet = sinan.download(files)

98243it [00:00, 8815647.77it/s]

In [6]:
df = None
for p in parquet:
    p.to_dataframe()
    df = pd.concat([df, p.to_dataframe()])

In [7]:
display(df)

,ID_MUNICIP,ID_UNIDADE,DT_NOTIFIC,CS_RACA,CS_ESCOLAR,NU_ANO,SEM_NOT,SG_UF_NOT,ID_REGIONA,DT_SIN_PRI,...,DT_ENCERRA,DT_DIGITA,DT_TRANSUS,DT_TRANSDM,DT_TRANSSM,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H
0,2708006,2004054,2004-01-26,4,3,2004,042004,AL,008,2004-01-20,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2704302,0008133,2004-02-04,,,2004,052004,AL,,2004-01-02,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2704302,2720035,2004-01-06,4,9,2004,012004,AL,001,2003-12-30,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2704302,2720035,2004-01-07,1,9,2004,012004,AL,001,2004-01-01,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2704302,2720035,2004-01-02,4,9,2004,532003,AL,001,2004-01-01,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,320530,11746,2024-12-16,4,<NA>,2024,202450,32,32002,2024-12-16,...,20241218,20241216,,,,,,,,
2267,320520,2445069,2024-12-27,4,<NA>,2024,202451,32,32002,2024-12-25,...,20250101,20241227,,,,,,,,
2268,320530,11800,2024-12-30,4,<NA>,2024,202452,32,32002,2024-12-29,...,20241231,20241230,,,,,,,,
2269,320530,11738,2024-11-17,3,<NA>,2024,202446,32,32002,2024-11-16,...,20250108,20241117,,,,,,,,
2270,320530,11738,2024-07-03,4,<NA>,2024,202426,32,32002,2024-07-02,...,20240718,20240703,,,,,,,,

In [8]:
df.to_csv('/content/malaria.csv', index=False) # criando um csv só da Malária

##**Parte 1 - Análise Exploratória de Dados**

##*Panorama Geral do Dataset*

In [9]:
print("Shape:", df.shape)
df.info()
df.describe()

Shape: (68320, 102)
<class 'pandas.core.frame.DataFrame'>
Index: 68320 entries, 0 to 2270
Columns: 102 entries, ID_MUNICIP to NU_LOTE_H
dtypes: object(2), string(100)
memory usage: 53.7+ MB

,ID_MUNICIP,ID_UNIDADE,DT_NOTIFIC,CS_RACA,CS_ESCOLAR,NU_ANO,SEM_NOT,SG_UF_NOT,ID_REGIONA,DT_SIN_PRI,...,DT_ENCERRA,DT_DIGITA,DT_TRANSUS,DT_TRANSDM,DT_TRANSSM,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H
count,68320,68320,68320,68320,12026,68320,68320,68320,68320,68320,...,56294,56294,56294,56294,56294,56294,56294,56294,56294,56294
unique,2642,6183,7216,7,8,21,1203,45,300,7764,...,591,4826,1525,668,3989,1,847,569,1,1
top,330455,2506661,2018-08-09,4,3,2018,201832,32,,2018-08-09,...,,,,,,,,,,
freq,3676,2805,464,28141,2996,7939,1917,9654,10892,437,...,55101,216,53828,55126,34713,56294,53848,51751,56294,56294

In [10]:
list = df.columns.tolist()
list.sort()
print(list)

['AMALARIA', 'ANO_NASC', 'ANT_DT_INV', 'ARTEI', 'ARTEM', 'ARTEMI', 'ARTESU', 'ASSINTOM', 'AT_ATIVIDA', 'AT_LAMINA', 'AT_SINTOMA', 'CALAFRIO', 'CD_OUTRO', 'CLASSI_FIN', 'CLIND', 'CLINDI', 'CLI_OUTRO', 'CLOROQ', 'CLOROQI', 'COMUNINF', 'CON_CLASSI', 'CON_CONFIR', 'CON_DOENCA', 'CON_DT_ENC', 'CON_DT_OBI', 'CON_EVOLUC', 'CON_INF_MU', 'CON_INF_PA', 'CON_INF_UF', 'COPAISINF', 'COUFINF', 'CS_ESCOLAR', 'CS_ESCOL_N', 'CS_GESTANT', 'CS_RACA', 'CS_SEXO', 'DEXAME', 'DINTERNA', 'DOXOCI', 'DSTRAESQUE', 'DTRATA', 'DTTRANSFU', 'DT_DIGITA', 'DT_ENCERRA', 'DT_INVEST', 'DT_NOTIFIC', 'DT_SIN_PRI', 'DT_TRANSDM', 'DT_TRANSRM', 'DT_TRANSRS', 'DT_TRANSSE', 'DT_TRANSSM', 'DT_TRANSUS', 'FEBRE', 'GESTANTE', 'HOSPITAL', 'ID_AGRAVO', 'ID_DG_NOT', 'ID_EV_NOT', 'ID_MN_RESI', 'ID_MUNICIP', 'ID_OCUPA_N', 'ID_PAIS', 'ID_REGIONA', 'ID_RG_RESI', 'ID_UNIDADE', 'IN_VINCULA', 'LOC_INF', 'MEFLOQ', 'MINTERNA', 'MTRANSFU', 'NDUPLIC', 'NU_ANO', 'NU_IDADE', 'NU_IDADE_N', 'NU_LOTE_H', 'NU_LOTE_I', 'NU_LOTE_V', 'OCUPACAO', 'PCRUZ', 'PMALARIA', 'PMM', 'PRIMAQ', 'PTRANSFU', 'PUSUARIO', 'QUININO', 'QUININOI', 'RESULT', 'SEM_NOT', 'SEM_PRI', 'SG_UF', 'SG_UF_NOT', 'SOUTROS', 'SUDORESE', 'TETRAC', 'TPAUTOCTO', 'TP_NOT', 'TRANSFU', 'TRA_ESQUEM', 'UFINTERNA', 'UFTRANSFU', 'UTRANSFU']

##*Avaliando os Dados Faltantes*

In [11]:
df = pd.read_csv("malaria.csv", low_memory=False, na_values=["<NA>", "NULL", "", "Ignorado", "NaN"])

missing_percent = (df.isna().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    "Coluna": missing_percent.index,
    "Percentual (%)": missing_percent.values
}).sort_values(by="Percentual (%)", ascending=False)

missing_df

         Coluna  Percentual (%)
100   NU_LOTE_V           100.0
101   NU_LOTE_H           100.0
78    DT_INVEST           100.0
97   DT_TRANSRM           100.0
69   IN_VINCULA           100.0
..          ...             ...
9    DT_SIN_PRI             0.0
15      ID_PAIS             0.0
0    ID_MUNICIP             0.0
2    DT_NOTIFIC             0.0
5        NU_ANO             0.0

[102 rows x 2 columns]

In [12]:
print(list) #PMALARIA AMALARIA??? - nada sobre no pdf de descrição do dataset, provavelmente não é tão relevante

['AMALARIA', 'ANO_NASC', 'ANT_DT_INV', 'ARTEI', 'ARTEM', 'ARTEMI', 'ARTESU', 'ASSINTOM', 'AT_ATIVIDA', 'AT_LAMINA', 'AT_SINTOMA', 'CALAFRIO', 'CD_OUTRO', 'CLASSI_FIN', 'CLIND', 'CLINDI', 'CLI_OUTRO', 'CLOROQ', 'CLOROQI', 'COMUNINF', 'CON_CLASSI', 'CON_CONFIR', 'CON_DOENCA', 'CON_DT_ENC', 'CON_DT_OBI', 'CON_EVOLUC', 'CON_INF_MU', 'CON_INF_PA', 'CON_INF_UF', 'COPAISINF', 'COUFINF', 'CS_ESCOLAR', 'CS_ESCOL_N', 'CS_GESTANT', 'CS_RACA', 'CS_SEXO', 'DEXAME', 'DINTERNA', 'DOXOCI', 'DSTRAESQUE', 'DTRATA', 'DTTRANSFU', 'DT_DIGITA', 'DT_ENCERRA', 'DT_INVEST', 'DT_NOTIFIC', 'DT_SIN_PRI', 'DT_TRANSDM', 'DT_TRANSRM', 'DT_TRANSRS', 'DT_TRANSSE', 'DT_TRANSSM', 'DT_TRANSUS', 'FEBRE', 'GESTANTE', 'HOSPITAL', 'ID_AGRAVO', 'ID_DG_NOT', 'ID_EV_NOT', 'ID_MN_RESI', 'ID_MUNICIP', 'ID_OCUPA_N', 'ID_PAIS', 'ID_REGIONA', 'ID_RG_RESI', 'ID_UNIDADE', 'IN_VINCULA', 'LOC_INF', 'MEFLOQ', 'MINTERNA', 'MTRANSFU', 'NDUPLIC', 'NU_ANO', 'NU_IDADE', 'NU_IDADE_N', 'NU_LOTE_H', 'NU_LOTE_I', 'NU_LOTE_V', 'OCUPACAO', 'PCRUZ', 'PMALARIA', 'PMM', 'PRIMAQ', 'PTRANSFU', 'PUSUARIO', 'QUININO', 'QUININOI', 'RESULT', 'SEM_NOT', 'SEM_PRI', 'SG_UF', 'SG_UF_NOT', 'SOUTROS', 'SUDORESE', 'TETRAC', 'TPAUTOCTO', 'TP_NOT', 'TRANSFU', 'TRA_ESQUEM', 'UFINTERNA', 'UFTRANSFU', 'UTRANSFU']

In [13]:
print(df['AMALARIA'].unique()) # Não entendi

['1A  ' nan '60D ' '34D ' '02M ' '45D ' '03M ' '3M  ' '7M  ' 'M   ' '05M '
 '10D ' '20A ' '09M ' '1M  ' '06M ' '12A ' '01A ' '21D ' '15A ' '2A  '
 '17A ' 'A   ' '13A ' '04M ' '02A ' '01M ' '5M  ' '2M  ' '10M ' '11M '
 '03A ' '29A ' '10A ' '56D ' '6M  ' '08M ' '5A  ' '29D ' '05A ' '4M  '
 '3A  ' '11A ' '15D ' '9A  ' '8A  ' '46A ' '45A ' '37A ' '+-2A' '06 M'
 '71D ' '55D ' '12M ' '42D ' '14A ' '04A ' 'D   ' '60A ' '49A ' '25A '
 '105D' '27D ' '07A ' '30D ' '40D ' '12D ' '6A  ' '06A ' '70D ' '08A '
 '67 D' '30A ' '40A ' '03  ' '25D ' 'd   ' '65A ' '36A ' '26A ' '07M '
 'MM  ' '0   ' '9   ' '24A ' '11D ' '42A ' '54  ' '00  ' '9M  ' '22A '
 '1   ' '20D ' '21A ' '1,5A' '19D ' '59M ' '52D ' '41D ' '59D ' '8M  '
 '80D ' '50D ' '23A ' '18A ' '15M ' '24D ' '09D ' '73D ' '90D ' '5D  '
 '35D ' '7A  ' '13M ' '6D  ' '9D  ' '36D ' '4A  ' '58D ' '48D ' '50A '
 '16A ' '49D ' '176D' '189D' '26D ' '59A ' '18M ' '19A ' '04I ' '23D '
 ' A  ' '32D ' '03aA' '1D  ' '.   ' '18  ' '45 D' '04 A' '28 A' '39D '
 '06  ' 'I   ' '09A ' '02  ' '16D ' '66A ' '16M ' '14D ' '110D' '65D '
 '05D ' '51D ' '7 A ' '28D ' '46D ' 'simA' '4,5M' '41A ' '32A ' '17D '
 '35A ' '43A ' '03D ' '30M ' '04  ' '66D ' '38D ' '81A ' '70  ' '39A '
 '88  ' '06D ' '86A ' '89  ' '86  ' '3   ' '26 D' '7 M ' '20 D' '07D '
 'AA  ' '3 M ' '95A ' '62D ' '08D ' '78D ' '22D ' '44A ' '35  ' '63D '
 '13D ' '98D ' '53D ' '70A ' '7D  ' '79D ' '19M ' '82D ' 'aA  ' '2 M '
 '75D ' '05 M' '14M ' '4D  ' '38A ' '43D ' '25M ' '09 M' '6   ' '04D '
 '64A ' '85D ' '63A ' '62M ' '3  M' '24 M' '77M ' '3I  ' '20M ' '1a6M'
 'm   ' '89A ' '?   ' '52A ' '86D ' '99  ' '00M ' '100D' '72D ' '180D'
 '58A ' '119D' '60 D' '8 M ' '45  ' '34M ' '08 D' '33D ' '20  ' '2   '
 '31A ' '+ 1A' '12 A' '2D  ' '40M ' '0A  ' '60M ' '18 D' '26M ' '01 M']

##*Remover colunas com mais de 80% de dados faltantes*

In [14]:
# Mantendo as colunas importantes antes da remoção, mesmo se possuírem mais de 80% <NA>

old_df = df.copy()

cols_importantes = [
    "DT_NOTIFIC",
    "SG_UF_NOT",
    "ID_MUNICIP",
    "NU_IDADE_N",
    "CS_SEXO"
]

# calcular proporção de NaN
missing_ratio = df.isnull().mean()

# definir threshold
threshold = 0.8

# colunas para remover (exceto importantes)
cols_removidas = missing_ratio[
    (missing_ratio >= threshold) & (~missing_ratio.index.isin(cols_importantes))
].index

# colunas mantidas
cols_mantidas = df.columns.difference(cols_removidas)

# logs
print(f"Total de colunas antes: {df.shape[1]}")
print(f"Colunas removidas: {len(cols_removidas)}")
print(f"Colunas restantes: {len(cols_mantidas)}")

print("\nExemplo de colunas removidas:")
print(cols_removidas[:10])

# aplicar remoção
df = df[cols_mantidas].copy()

Total de colunas antes: 102
Colunas removidas: 66
Colunas restantes: 36

Exemplo de colunas removidas:
Index(['CS_ESCOLAR', 'NU_IDADE', 'ID_DG_NOT', 'ID_EV_NOT', 'ANT_DT_INV',
       'OCUPACAO', 'TRANSFU', 'DTTRANSFU', 'UTRANSFU', 'UFTRANSFU'],
      dtype='object')

In [15]:
df

,ANO_NASC,AT_ATIVIDA,AT_LAMINA,AT_SINTOMA,CLASSI_FIN,COPAISINF,CS_ESCOL_N,CS_GESTANT,CS_RACA,CS_SEXO,...,NU_LOTE_I,PCRUZ,RESULT,SEM_NOT,SEM_PRI,SG_UF,SG_UF_NOT,TPAUTOCTO,TP_NOT,TRA_ESQUEM
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,M,...,NaN,3.0,4.0,42004.0,32004.0,AL,AL,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M,...,NaN,NaN,NaN,52004.0,532003.0,AL,AL,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,M,...,NaN,4.0,4.0,12004.0,532003.0,AL,AL,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,M,...,NaN,3.0,4.0,12004.0,532003.0,AL,AL,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,F,...,NaN,NaN,2.0,532003.0,532003.0,AL,AL,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68315,1996.0,11.0,1.0,1.0,2.0,0.0,6.0,6.0,4.0,M,...,NaN,NaN,1.0,202450.0,202450.0,32,32,NaN,2.0,NaN
68316,2022.0,99.0,1.0,1.0,2.0,0.0,10.0,6.0,4.0,M,...,NaN,NaN,1.0,202451.0,202451.0,32,32,NaN,2.0,NaN
68317,2013.0,99.0,1.0,1.0,2.0,0.0,9.0,6.0,4.0,M,...,NaN,NaN,1.0,202452.0,202452.0,32,32,NaN,2.0,NaN
68318,1997.0,11.0,1.0,1.0,1.0,177.0,9.0,6.0,3.0,M,...,NaN,5.0,2.0,202446.0,202445.0,32,32,2.0,2.0,12.0
68319,1992.0,11.0,1.0,1.0,1.0,177.0,9.0,6.0,4.0,M,...,NaN,3.0,4.0,202426.0,202426.0,32,32,2.0,2.0,1.0

In [16]:
# Separando em variáveis categóricas e numéricas

num_cols = df.select_dtypes(include=["int64", "float64"]).columns
cat_cols = df.select_dtypes(include=["object"]).columns

for col in num_cols:
    df.loc[:, col] = df[col].fillna(df[col].median())

for col in cat_cols:
    df.loc[:, col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum().sort_values(ascending=False).head(10)

ANO_NASC      0
AT_ATIVIDA    0
AT_LAMINA     0
AT_SINTOMA    0
CLASSI_FIN    0
COPAISINF     0
CS_ESCOL_N    0
CS_GESTANT    0
CS_RACA       0
CS_SEXO       0
dtype: int64